defaults:
  - corpus: config_toefl

hf_token: null

training_args:
  mixed_precision: 'no'
  gradient_accumulation_steps: 1
  run_iter: 5
  path_resume_checkpoint: ""
  checkpointing_steps: epoch

exp_args:
  sample_num: 500
  top_k: 5

model:
  llm_id: microsoft/Phi-3.5-mini-instruct
